### ISSUE TITLE
[BUG]Couldn't set custom cache_agents for yurthub

### ISSUE THREAD

**Issue by longhua** [openyurtio/yurtcluster-operator#11]
**What happened**:
I've converted K8S 1.21.8 cluster, however couldn't add custom cache_agents for my application.

**What you expected to happen**:
I can add custom cache_agents to cache my application requests.

**How to reproduce it (as minimally and precisely as possible)**:
1. Convert a cluster using yurtcluster operator 0.6.0
2. Edit yurt-hub-cfg ConfigMap: kubectl edit cm yurt-hub-cfg -n kube-system
3. Wait for more than 1 minute
4. Check yurt-hub-cfg ConfigMap: kubectl get cm yurt-hub-cfg -n kube-system -o yaml
Result: yurt-hub-cfg is reverted to original version

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
yurtcontroller-manager version: projectinfo.Info{GitVersion:"v0.6.0", GitCommit:"7df5fd6", BuildDate:"2022-01-12T07:19:07Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
- YurtCluster Operator version:
0.6.0（master branch db51c4786c866e84e92a2001af8f577873b369ca）
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
- Kernel (e.g. `uname -a`):
Linux k8s-master 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by SataQiu** [comment]
@longhua Thanks for reporting this.
This is really a bug, and I have sent a PR to fix it.

For a workaround(if you do not want to upgrade operator), you can add an annotation into the `yurt-hub-cfg` ConfigMap:
```sh
#kubectl edit cm -n kube-system yurt-hub-cfg        
metadata:
  annotations:
    operator.openyurt.io/skip-reconcile: "true"
```
